const config = {
  mongoURL: process.env.MONGO_URL || 'mongodb://localhost:27017/giftests',
  port: process.env.PORT || 3000,
  facebook: {
    clientID: process.env.FB_CLIENT_ID || '',
    clientSecret: process.env.FB_CLIENT_SECRET || '',
    callbackURL: process.env.FB_CALLBACK_URL || '',
  },
  sessionSecret: process.env.SESSION_SECRET || 'AnimatedtestSESS',
  cookie: {
    maxAge: 24 * 60 * 60 * 1000,
  },
  morphConfig: {
    debugMode: 'y',
    showAPITrace: 'n',
    lang: 'en',
    nullTemplate: 'y',
    background: 'http://dev01.dev103.social-net.me:8080/imagecreator/temp/morphimgbgd.png',
    imgType: 'aniGIF',
    outputParams: {
      frameCount: '10',
      frameDelay_ms: '500',
    },
    custImg2_effectA_param: {
      op: 'faceDetect',
      drawBox: 'n',
      cropToFace: 'y',
      debugCmd: 'n',
      detectMethod: 'accurate_2',
    },
    custImg2_effect: 'A',
    custImg2_w: 200,
    custImg2_h: 200,
    custImg3_effectA_param: {
      op: 'faceDetect',
      drawBox: 'n',
      cropToFace: 'y',
      debugCmd: 'n',
      detectMethod: 'accurate_2',
    },
    custImg3_effect: 'B',
    custImg3_w: 200,
    custImg3_h: 200,
    custImg2_internalUse: 'y',
    custImg3_internalUse: 'y',
    custImg4_url: 'morphImg1',
    custImg4_x: 0,
    custImg4_y: 40,
    custImg4_w: 260,
    custImg4_h: 250,
    custImg4_type: 'morphImg',
    morphImg1: {
      srcCustImgID: '2',
      destCustImgID: '3',
      w: '200',
      h: '200',
      debugCmd: 'n',
      morphIn2Direction: 'y',
    },
  },
};

export default config;
