const config = {
  mongoURL: process.env.MONGO_URL || 'mongodb://localhost:27017/giftests',
  port: process.env.PORT || 3000,
  facebook: {
    apiVersion: 'v2.9',
    clientID: process.env.FB_CLIENT_ID || '',
    clientSecret: process.env.FB_CLIENT_SECRET || '',
    callbackURL: process.env.FB_CALLBACK_URL || '',
  },
  aws: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
    region: process.env.AWS_REGION || 'us-east-2',
    s3Bucket: process.env.AWS_S3_BUCKET || 'animated.test.com',
    s3Url: process.env.AWS_S3_URL || 'http://animatedtest.com',
    s3Folder: process.env.AWS_S3_FOLDER || 'dev',
  },
  sessionSecret: process.env.SESSION_SECRET || 'AnimatedtestSESS',
  cookie: {
    maxAge: 24 * 60 * 60 * 1000,
  },
  morphApiUrl: process.env.MORPH_API_URL || 'http://localhost',
  faceDetectConfig: {
    apiKey: process.env.MORPH_API_KEY || '',
    debugMode: 'n',
    showAPITrace: 'n',
    lang: 'en',
    nullTemplate: 'y',
    custImg3_effectB_param: {
      op: 'faceDetect',
      drawBox: 'n',
      cropToFace: 'y',
      debugCmd: 'n',
      detectMethod: 'accurate_2',
      returnFaceDetectResultOnly: 'y',
    },
    custImg3_effect: 'B',
    custImg3_w: 200,
    custImg3_h: 200,
  },
  morphConfig: {
    apiKey: process.env.MORPH_API_KEY || '',
    debugMode: 'n',
    showAPITrace: 'n',
    lang: 'en',
    nullTemplate: 'y',
    background: 'http://dev01.dev103.social-net.me:8080/imagecreator/temp/morphimgbgd.png',
    imgType: 'aniGIF',
    outputParams: {
      frameCount: '10',
      frameDelay_ms: '500',
    },
    custImg2_effectA_param: {
      op: 'faceDetect',
      drawBox: 'n',
      cropToFace: 'y',
      debugCmd: 'n',
      detectMethod: 'accurate_2',
      cropToFaceRatio: '1:1',
    },
    custImg2_effect: 'A',
    custImg2_w: 200,
    custImg2_h: 200,
    custImg3_effectB_param: {
      op: 'faceDetect',
      drawBox: 'n',
      cropToFace: 'y',
      debugCmd: 'n',
      detectMethod: 'accurate_2',
      cropToFaceRatio: '1:1',
    },
    custImg3_effect: 'B',
    custImg3_w: 200,
    custImg3_h: 200,
    custImg2_internalUse: 'y',
    custImg3_internalUse: 'y',
    custImg4_url: 'morphImg1',
    custImg4_x: 0,
    custImg4_y: 40,
    custImg4_w: 260,
    custImg4_h: 250,
    custImg4_type: 'morphImg',
    morphImg1: {
      srcCustImgID: '2',
      destCustImgID: '3',
      w: '200',
      h: '200',
      debugCmd: 'n',
      morphIn2Direction: 'y',
    },
  },
};

export default config;
